### ISSUE TITLE
"Brew brewdle" - Invalid brewfile

### ISSUE THREAD

**Issue by k5njm** [moubry/dotfiles#1]
Hi, working through the process in the readme, and getting stuck at this step to install the bundle. I understand brew's bundle functionality has changed lately, but it looks like brewdler is expecting to process "Brewfile". I'm not sure from the output if it's failing to point to your Brewfile or if it's having an issue while parsing the file.

```
MacBook-Pro:dotfiles nick$ brew tap Homebrew/brewdler
    Warning: Already tapped!
MacBook-Pro:dotfiles nick$ pwd
    /Users/nick/Projects/dotfiles
MacBook-Pro:dotfiles nick$ brew brewdle
    Error: Invalid Brewfile.
```

**Comment by k5njm** [comment]
After some trial and error, it seems the offending line that causes "Invalid Brewfile" is:
`brew tap caskroom/fonts`

I'm not sure why you can't use tap in a Brewfile, but I can run that one line manually.

**Comment by moubry** [comment]
@kd5ftn I fixed this stuff. Try again?

**Comment by moubry** [comment]
@kd5ftn Pull the new files and try again.
